#!/bin/bash

CONFIG_FILENAME="/home/bread/src/proxypush/.ppush/master"
PUSHER_NAME=$1
REPO_ROOT=$2||""
OPTIONS=$3||""

# print the list of configs from config file
get_configs()
{
   awk -F '[][]' '
      NF==3 && $0 ~ /^\[.*\]/ { print $2 }
   ' ${CONFIG_FILENAME}
}

# set variables (optionaly prefixed by var_prefix) from config in config file
set_config_vars()
{
   typeset config=$1
   typeset var_prefix=$2
   typeset config_vars

   config_vars=$( 
        awk -F= -v Config="${config}" -v Prefix="${var_prefix}" '
        BEGIN { 
           Config = toupper(Config);
           patternConfig = "\\[" Config "]";
        }
        toupper($0)  ~ patternConfig,(/\[/ && toupper($0) !~ patternConfig)  { 
           if (/\[/ || NF <2) next;
           sub(/^[[:space:]]*/, "");
           sub(/[[:space:]]*=[[:space:]]/, "=");
           print Prefix $0;
        } ' ${CONFIG_FILENAME} )

   eval "${config_vars}"
}

get_pusher_config()
{
    # if [ -z "${2}" ]
    for cfg in $(get_configs)
    do
        if [ "${1}" == "${cfg}" ]
        then
            unset $(set | awk -F= '/^cfg_/  { print $1 }') cfg_
            set_config_vars ${cfg} cfg_
            set | grep ^cfg_
        fi
    done
}


if [ "$1" == "--push" ]; then
    source $HOME/.ppush/push
    echo "Retrieving repo from master node..."
    rsync $master_username@$master_hostname:"/home/$master_username/.ppush/master" /tmp/ppush-maste
    eval `get_pusher_config $PUSHER_NAME`
    mkdir -P /tmp/ppush/$PUSHER_NAME
    rsync $master_username@$master_hostname:$REPO_ROOT /tmp/ppush/$PUSHER_NAME
    cd /tmp/ppush/$PUSHER_NAME
    echo "Pushing to remote..."
    eval "$cfg_command"
    rm /tmp/ppush-master
    rm -r /tmp/ppush/$PUSHER_NAME
    echo Done
    exit 1
else
    get_pusher_config $PUSHER_NAME
    echo "Asking $PUSHER_NAME to push..."
    ssh_command="ssh $cfg_username@$cfg_hostname -t \"$cfg_script_path --push $REPO_ROOT\""
    echo $ssh_command
    eval $ssh_command
    exit 1
fi